const test = require("node:test");
const assert = require("node:assert/strict");

const {
    isGeneratedPitchAccentSource,
    validateWordPitchAccentSource,
} = require("../src/services/wordPitchAccentVerificationService");

const sources = {
    "kanjium-cc-by-sa-4.0": {
        name: "Kanjium pitch accent database",
        license: "CC BY-SA 4.0",
    },
    "voicevox-nemo-accent-query": {
        name: "VOICEVOX Nemo accent query",
        license: "VOICEVOX Nemo terms",
    },
    "voicevox-nemo-reading-query": {
        name: "VOICEVOX Nemo reading accent query",
        license: "VOICEVOX Nemo terms",
    },
    "wiktionary-ja-pronunciation": {
        name: "Wiktionary Japanese pronunciation entries",
        license: "CC BY-SA 4.0 / GFDL",
    },
};

test("validateWordPitchAccentSource accepts exact Kanjium word-reading evidence", () => {
    const failures = validateWordPitchAccentSource({
        word: "生ビール",
        reading: "なまびーる",
        sources,
        sourceEntry: {
            pattern: "3 [nakadaka]",
            sourceId: "kanjium-cc-by-sa-4.0",
            sourceWord: "生ビール",
            sourceReading: "なまビール",
            sourceAccent: "3",
        },
    });

    assert.deepEqual(failures, []);
});

test("validateWordPitchAccentSource rejects Kanjium source rows for a different word or accent", () => {
    const failures = validateWordPitchAccentSource({
        word: "雨",
        reading: "あめ",
        sources,
        sourceEntry: {
            pattern: "1 [atamadaka]",
            sourceId: "kanjium-cc-by-sa-4.0",
            sourceWord: "飴",
            sourceReading: "あめ",
            sourceAccent: "0",
        },
    });

    assert.match(failures.join("\n"), /sourceWord does not match/);
    assert.match(failures.join("\n"), /sourceAccent does not match/);
});

test("validateWordPitchAccentSource validates declared external source identity", () => {
    assert.deepEqual(validateWordPitchAccentSource({
        word: "一",
        reading: "いち",
        sources,
        sourceEntry: {
            pattern: "2 [odaka]",
            sourceId: "wiktionary-ja-pronunciation",
            sourceWord: "一",
            sourceReading: "いち",
            sourceAccent: "2",
        },
    }), []);

    const failures = validateWordPitchAccentSource({
        word: "七",
        reading: "なな",
        sources,
        sourceEntry: {
            pattern: "1 [atamadaka]",
            sourceId: "wiktionary-ja-pronunciation",
            sourceWord: "七",
            sourceReading: "しち",
            sourceAccent: "2",
        },
    });

    assert.match(failures.join("\n"), /sourceReading does not match/);
    assert.match(failures.join("\n"), /sourceAccent does not match/);
});

test("validateWordPitchAccentSource validates VOICEVOX written and reading query identity", () => {
    assert.deepEqual(validateWordPitchAccentSource({
        word: "一",
        reading: "いち",
        sources,
        sourceEntry: {
            pattern: "2 [odaka]",
            sourceId: "voicevox-nemo-accent-query",
            sourceQuery: "一",
            generatedReading: "いち",
        },
    }), []);

    assert.deepEqual(validateWordPitchAccentSource({
        word: "公園の中",
        reading: "こうえんのなか",
        sources,
        sourceEntry: {
            pattern: "5 [odaka] / 1 [atamadaka]",
            sourceId: "voicevox-nemo-reading-query",
            sourceQuery: "こうえんのなか",
            generatedReading: "こおえんのなか",
        },
    }), []);
});

test("isGeneratedPitchAccentSource identifies generated pitch sources", () => {
    assert.equal(isGeneratedPitchAccentSource({ sourceId: "voicevox-nemo-accent-query" }), true);
    assert.equal(isGeneratedPitchAccentSource({
        sourceId: "custom-source",
        source: { attribution: "Accent analysis generated by a local engine." },
    }), true);
    assert.equal(isGeneratedPitchAccentSource({
        sourceId: "kanjium-cc-by-sa-4.0",
        source: sources["kanjium-cc-by-sa-4.0"],
    }), false);
});

test("validateWordPitchAccentSource rejects undeclared sources", () => {
    const failures = validateWordPitchAccentSource({
        word: "雨",
        reading: "あめ",
        sources,
        sourceEntry: {
            pattern: "1 [atamadaka]",
            sourceId: "unknown-source",
        },
    });

    assert.match(failures.join("\n"), /not declared/);
});
